server:
  port: 8081

spring:
  kafka:
    bootstrap: ${KAFKA_RESERVATION_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      topic:
        create-order: create-order
        create-order-status: status
        kafkaMessageGroupId: "get"


