version: '3'
services:
  postgres:
    container_name: app
    image: postgres:15.5
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_news
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql