spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
#    open-in-view: false #?????? ?? ?????????? ? ?????????????? ??
  datasource:
#    url: jdbc:postgresql://172.30.38.105:5432/app_news
    url: jdbc:postgresql://localhost:5430/app_news
    username: postgres
    password: postgres
    hikari:
      schema: app_news
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_news
      connection-timeout: 10000